### PR TITLE
Character Rando rework

### PR DESCRIPTION
**Pull request by coffeemancy**
This reworks how Duplicate Characters works by moving to a new top-level flag for "Character Rando".

When Character Rando is enabled, all character identities have a random character model assigned. This abides the character assignment matrix (like Duplicate Characters does), but exactly one of each character model is assigned (e.g. no duplicates).

This can lead to some interesting play like needing "Frog" and "Magus" for Legacy of Cyrus, but "Frog" is an Ayla and "Magus" is a Robo, however, it avoids scenarios like "oops all Marle".

Duplicate Characters flag now becomes an option under Character Randomization (along with Duplicate Techs).

## Updates

* Adds new top-level flag `CHAR_RANDO` (`-rc`) to randomize characters (without duplicates)
* Moves `DUPLICATE_CHARS` from General to RC tab in TK GUI (requiring `CHAR_RANDO`)
* Updates validation in TK GUI to assure that at least one character identity is associated with each character model when `CHAR_RANDO` is used (without `DUPLICATE_CHARS`, which allows for missing models)

### CLI

Tested along with [spoilers fix for CLI](https://github.com/Pseudoarc/jetsoftime/pull/17).

1. Generate seed with Char Rando, spoiler shows uniquely randomized characters (each identity has a unique model)

```bash
➜  python randomizer.py -i ct.sfc -rc --spoilers
output ROM: ct.sfc.st.n.rc.leapershadow.sfc
spoilers: ct.sfc.st.n.rc.leapershadow.spoilers.txt

➜ grep "Char.*Loc" ./ct.sfc.st.n.rc.leapershadow.spoilers.txt -A8 
Character Locations
-------------------
Starter 1           Marle reassigned Robo
Starter 2           Frog reassigned Frog
Cathedral           Crono reassigned Marle
Castle              Lucca reassigned Ayla
Frogs Burrow        Magus reassigned Crono
Dactyl Nest         Ayla reassigned Lucca
Proto Dome          Robo reassigned Magus
```

2. Generate seed with Char Rando + Duplicate Chars, spoiler shows dupes allowed

```bash
➜ python randomizer.py -i ct.sfc -dc --spoilers     
output ROM: ct.sfc.st.n.dc.flunkyzeal.sfc
spoilers: ct.sfc.st.n.dc.flunkyzeal.spoilers.txt
➜ grep "Char.*Loc" ./ct.sfc.st.n.dc.flunkyzeal.spoilers.txt -A8         
Character Locations
-------------------
Starter 1           Marle reassigned Marle
Starter 2           Frog reassigned Frog
Cathedral           Lucca reassigned Lucca
Castle              Ayla reassigned Ayla
Frogs Burrow        Robo reassigned Robo
Dactyl Nest         Magus reassigned Magus
Proto Dome          Crono reassigned Crono
```

### TK GUI

Tested along with [spoilers fix for CLI](https://github.com/Pseudoarc/jetsoftime/pull/17).

Testing RC validation logic:

1. Enable Character Rando (RC tab becomes enabled)
2. Deselect all models for an identity, Generate shows error
3. Deselect all identities for a model, Generate shows error
4. Enable Duplicate Chars, Generate works (don't need all models to have an identity)
5. Deselect all models for an identity, Generate shows error

[char-rando-tk-gui-validation.webm](https://github.com/Pseudoarc/jetsoftime/assets/3493534/9f1e1834-3e53-4b72-8b1e-7bbf6838d69f)

### Web GUI

Tested alongside PR to `ctjot_web_generator`: https://github.com/Anguirel86/ctjot_web_generator/pull/18

## Notes

* This maintains the `-dc` flag option (which forces `-rc` on as well) for backwards compatibility (e.g. don't need to synchronize these changes with the web GUI, necessarily), although if desired, that could be removed.
* Mystery settings: I've initially set the chance for Char Rando at 50% in mystery settings (which is double the 25% of Dupe Chars), but if a different value makes more sense, let me know, I'll update it.
* This now automatically enables `CHAR_RANDO` if `DUPLICATE_CHARS` is enabled. If `DUPLICATE_TECHS` is enabled, it will enable both `CHAR_RANDO` and `DUPLICATE_CHARS`

### CODE REVIEW

**Comment by Pseudoarc** [comment]
I don't have much to add to this.  Making shuffled identities the default and allowing duplicates through a flag opens up a lot of possibilities.  This looks great and ready to merge, but I'll wait until after this weekend's web update along with the spoiler log fix.

**Comment by coffeemancy** [comment]
Did some more playing of this (just apparently hadn't run into it) but not sure why (trying to figure out) but debugging:

* Playing with just RC, if a character gets identified as a non-magic user (Ayla, Robo), and you go to Spekkio, that character does not learn magic (e.g. a Crono model named Ayla, or a Frog model named Robo does not learn magic)
* Was able to reproduce several times in RC seeds
* Independently tried with DC and for some reason it doesn't have this problem
* I'm thinking the bug might be somewhere in the permutation / choices / choices_list being set differently for RC vs DC (am investigating)

Going to close this PR to avoid merging it while digging in. Will re-open after I think I've fixed it.

**Comment by coffeemancy** [comment]
Okay this is the bit that looks suspect: https://github.com/Pseudoarc/jetsoftime/blob/beta/sourcefiles/randomizer.py#L1100-L1115

Gonna try fixing that section and see if any more references to `dup_chars` or `DUPLICATE_CHARS`.

Pretty funny because I've played several seeds and hadn't managed to hit this before.

**Comment by coffeemancy** [comment]
Fix in https://github.com/coffeemancy/jetsoftime/commit/a039a3a7e9e3e481cd9d83eaa51496901b081860.

Rebased and force-pushed so opened new PR: https://github.com/Pseudoarc/jetsoftime/pull/19

**Pull request closed without merging**
